Fix compilation error (missing virtual destructor)
Fixes:
pxCore/src/rtFileDownloader.cpp:623:16: error: deleting object of polymorphic class type ‘rtFileDownloader’ which has non-virtual destructor might cause undefined behavior [-Werror=delete-non-virtual-dtor]
         delete mInstance;
                ^~~~~~~~~
cc1plus: all warnings being treated as errors